language: node_js
node_js:
  - 12.17
  - 14
  - 15
sudo: false
before_install:
  - curl -f https://get.pnpm.io/v6.js | node - add --global pnpm
install:
  - pnpm install
script:
  - pnpm test
notifications:
  email: false
