name: CI

on: [push, pull_request]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  build:
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.platform }}-${{ matrix.node }}
      cancel-in-progress: true

    strategy:
      fail-fast: false
      matrix:
        node:
          - '12'
          - '16.14'
          - '18'
          - '20'
          - '21'
        platform:
          - ubuntu-latest
          - windows-latest

    name: '${{matrix.platform}} / Node.js ${{ matrix.node }}'
    runs-on: ${{matrix.platform}}

    steps:
    - name: Checkout Commit
      uses: actions/checkout@v3
    - name: Install pnpm
      uses: pnpm/action-setup@v2.4.0
      with:
        version: next-8
        standalone: true
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: 'pnpm'
    - name: Install
      run: pnpm install
    - name: Test
      run: pnpm test
